name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Decode service account
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > $HOME/serviceAccount.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy
        run: |
          firebase deploy --only hosting \
            --project timetobite-633d8 \
            --token "$(cat $HOME/serviceAccount.json)"
